/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void testroll() {

        int numRolls = 4;
        assertEquals(numRolls, Library.roll(numRolls).length, "The size test passed");
    }

    @Test
    public void testAverage(){
        int [] arr ={1,2,3};
        int av= 7;
        assertEquals( av, Library.avgArray(arr));
    }
}
