/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

    public static int [] roll(int n) {

        int[] rolls = new int[n];
        System.out.println(n);
        int [] number = new int [n];

        for (int i = 0; i < rolls.length; i++) {
            int random = (int) Math.ceil(Math.random() * 6);
            number[i]=random;

        }
        System.out.println(Arrays.toString(number));
        return number;
    }

    public static boolean containsDuplicates(int[] arry) {

        for (int itemAryOne = 0; itemAryOne < arry.length; itemAryOne++) {
            for (int itemAryTow = 0; itemAryTow < itemAryOne; itemAryTow++) {
                if (arry[itemAryOne] == arry[itemAryTow]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static double averageArry(int[] array) {
        double endAvg=0;
        double sumOfAr = 0;
        for (int value : array) {
            sumOfAr += value;
        }
        endAvg=sumOfAr / array.length;
        return endAvg;
    }

    public static int [] weeklyMonthTemperatures(int[][] arr) {
        double lowestArryAvg=0;
        double[] avarges = new double[arr.length];

        double finalAv = 0;
        for (int i = 0; i < arr.length; i++) {
            double sum = 0;
            for (int j = 0; j < arr[i].length; j++) {
                sum += arr[i][j];
            }
            avarges[i] = sum / arr[i].length;
        }
        lowestArryAvg=avarges[0];
        int finalArry=0;
        for (int i = 0; i < avarges.length; i++) {
           if(avarges[i]<lowestArryAvg){
               finalArry=i;
           }

        }

        return arr[finalArry];
    }

}


