/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

    public static void roll(int n) {

        int[] rolls = new int[n];
        System.out.println(n);
        ArrayList<Integer> number = new ArrayList<>();

        for (int i = 0; i < rolls.length; i++) {
            int random = (int) Math.ceil(Math.random() * 6);
            number.add(random);

        }
        System.out.println(number);
    }

    public static boolean containsDuplicates(int[] arry) {

        for (int itemAryOne = 0; itemAryOne < arry.length; itemAryOne++) {
            for (int itemAryTow = 0; itemAryTow < itemAryOne; itemAryTow++) {
                if (arry[itemAryOne] == arry[itemAryTow]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static void Average(int[] array) {
        double sumOfAr = 0;
        for (int value : array) {
            sumOfAr += value;
        }
        System.out.println(sumOfAr / array.length);
    }

    public static double weeklyMonthTemperatures(int[][] arr) {
        double[] avarges = new double[arr.length];

        double finalAv = 0;
        for (int i = 0; i < arr.length; i++) {
            double sum = 0;

            for (int j = 0; j < arr[i].length; j++) {

                sum += arr[i][j];
            }
            avarges[i] = sum / arr[i].length;
        }
        for (int i = 0; i < avarges.length; i++) {
            for (int j = 0; j < avarges.length; j++) {
                if (avarges[i] < avarges[j]) {
                    finalAv = avarges[i];
                }
            }
        }

        return finalAv;
    }

}


