/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Restaurant test = new Restaurant("ali",10.1);
        Restaurant test3= new ReviewRestorant("a",10,"a");
        System.out.println(test);


//        test3.toString();



    }
}
