/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        Path jsPath = Paths.get("app/src/main/resources/gates.js");

        System.out.println(Scaner(jsPath));
    }
    public static String Scaner(Path newPath) {
        String line;
        String err = "";
        int lineNum = 1;





        try (
                BufferedReader bufferedReader = Files.newBufferedReader(newPath)



        ) {


            while ((line = bufferedReader.readLine()) != null) {



                if (!(line.isBlank() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else") || line.endsWith(";")))
                    err += "Line " + lineNum + ": Missing semicolon.\n";


                lineNum++;
            }
        } catch (IOException ioException) {
            System.out.println(ioException.getMessage());
        }





        return err;
    }


}

