/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test void one() {

        Restaurant test = new Restaurant("mac","1");
        assertEquals("Restaurant{name='mac' \n" +
                ", stars=0 \n" +
                ", price='1' \n" +
                ", reviews=[] \n" +
                "}",test.toString(),"dd");
    }
    @Test void tow() {
        Review ss = new Review("ali","ali",5);
        assertEquals("Review{body='ali', author='ali' \n" +
                ", stars=5 \n",ss.toString(),"dd");
    }

    @Test void testReview(){
        Review fromCustmer= new Review("good","adham",4);



        assertEquals("Review{body='good', author='adham' \n" +
                ", stars=4 \n",fromCustmer.toString());


    }



    @Test void therd() {
        Shop shop=new Shop("shop","the Shop good",5);
        assertEquals("Shop{nameShop='shop', description='the Shop good', numDoller=5}",shop.toString(),"dd");
    }
    @Test void theater() {
        Theater theater = new Theater("ali");
        assertEquals("Theater{name='ali', reviewsArray=[Review{body='d', author='start' \n" +
                        ", stars=2 \n" +
                        ", Review{body='d', author='start' \n" +
                        ", stars=3 \n" +
                        ", Review{body='ss', author='start' \n" +
                        ", stars=1 \n" +
                        "], Movies=[b]}\n" +
                        "Restaurant{name='mac' \n" +
                        ", stars=0 \n" +
                        ", price='1' \n" +
                        ", reviews=[Review{body='d', author='start' \n" +
                        ", stars=2 \n" +
                        ", Review{body='ss', author='start' \n" +
                        ", stars=1 ]> ",
                theater.toString(),
                "dd");
    }
}